backend:
    name: git-gateway
    branch: main

local_backend: true
# logo_url: HAS TO BE URL

public_folder: "/images/uploads"
media_folder: "public/images/uploads"

collections:
  - name: "rentals"
    label: "Rentals"
    folder: "content/rentals"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Date Posted", name: "date_posted", widget: "datetime" }
      - { label: "Images", name: "images", widget: "list", fields: [{ label: "Image", name: "image", widget: "image" }] }