backend:
    name: git-gateway
    branch: main

local_backend: true
# logo_url: HAS TO BE URL

public_folder: "/images/uploads"
media_folder: "public/images/uploads"

collections:
  - name: "events"
    label: "Events"
    folder: "src/content/events"
    create: true
    format: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Event title", name: "title", widget: "string" }
      - { label: "Catchy description (Example: MARK YOUR CALENDERS FOR OCTOBER 26TH – IT’S GONNA BE A HALLOWEEN NIGHT YOU WON’T FORGET)", name: "description", widget: "text" }
      - { label: "Location/Venue", name: "location", widget: "string" }
      - { label: "Event date", name: "date", widget: "datetime" }
      - { label: "Link to ticket sale page (EventBrite etc)", name: "ticketLink", widget: "string" }
      - { label: "Banner image", name: "banner", widget: "image" }
      - { label: "Images (Gallery images taken during the event)", name: "images", widget: "list", fields: [{ label: "Image", name: "image", widget: "image" }] }