backend:
    name: github
    repo: Slobodan-Starcevic/loveless
    branch: main

local_backend: true
# logo_url: HAS TO BE URL

public_folder: "/images/uploads"
media_folder: "public/images/uploads"

collections:
  - name: "events"
    label: "Events"
    folder: "src/content/events"
    create: true
    format: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Event title", name: "title", widget: "string" }
      - { label: "Catchy description (Example: The end is nigh - are you coming with us on the last day on earth?)", name: "description", widget: "text" }
      - { label: "Location/Venue", name: "location", widget: "string" }
      - { label: "Event date", name: "date", widget: "datetime" }
      - { label: "Ticket page link", name: "ticketLink", widget: "string" }
      - { label: "Banner image", name: "banner", widget: "image" }
      - { label: "Gallery Images", name: "images", widget: "list", fields: [{ label: "Image", name: "image", widget: "image" }] }